### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by qq270755744** [Moriafly/SaltUI#12]
能不能实现AIMP和QQ类似的可以侧边或顶部隐藏和播放，播放时弹出当前播放的歌曲信息，播放歌曲时可以定义在哪个时间点开始播放，类似视频跳过开头的功能

**Comment by Moriafly** [comment]
您好，我不是很理解您的意思，可以详细描述下吗？以及您反馈的问题是对哪款软件的，本仓库为 UI 库。
